language: java
sudo: false

jdk:
  - openjdk10

jobs:
  include:
    - stage: test
      script:
        - mvn exec:java
    - stage : deploy
        script :
          - docker build -t brandonfl/model-ppc .
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker push brandonfl/model-ppc:latest
